name: Copy profile README to repository README
on:
  push:
    branches:
      - main
    paths:
      - "profile/README.md"

jobs:
  copy:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v6
      - name: Copy profile README to repository README
        id: copy
        run: |
          cp ./profile/README.md ./README.md
      - uses: stefanzweifel/git-auto-commit-action@v7
